package cn.hisdar.touchpaneltool.androidDevice;

public class KeyCode {
	public static final int KEYCODE_UNKNOWN = 1;
	//public static final int KEYCODE_MENU = 2;
	public static final int KEYCODE_SOFT_RIGHT = 3;
	public static final int KEYCODE_HOME = 3;
	public static final int KEYCODE_BACK = 4;
	public static final int KEYCODE_CALL = 6;
	public static final int KEYCODE_ENDCALL = 7;
	public static final int KEYCODE_0 = 8;
	public static final int KEYCODE_1 = 9;
	public static final int KEYCODE_2 = 10;
	public static final int KEYCODE_3 = 11;
	public static final int KEYCODE_4 = 12;
	public static final int KEYCODE_5 = 13;
	public static final int KEYCODE_6 = 14;
	public static final int KEYCODE_7 = 15;
	public static final int KEYCODE_8 = 16;
	public static final int KEYCODE_9 = 17;
	public static final int KEYCODE_STAR = 18;
	public static final int KEYCODE_POUND = 19;
	public static final int KEYCODE_DPAD_UP = 20;
	public static final int KEYCODE_DPAD_DOWN = 21;
	public static final int KEYCODE_DPAD_LEFT = 22;
	public static final int KEYCODE_DPAD_RIGHT = 23;
	public static final int KEYCODE_DPAD_CENTER = 24;
	public static final int KEYCODE_VOLUME_UP = 24;
	public static final int KEYCODE_VOLUME_DOWN = 25;
	public static final int KEYCODE_POWER = 26;
	public static final int KEYCODE_CAMERA = 28;
	public static final int KEYCODE_CLEAR = 30;
	public static final int KEYCODE_A = 31;
	public static final int KEYCODE_B = 32;
	public static final int KEYCODE_C = 33;
	public static final int KEYCODE_D = 34;
	public static final int KEYCODE_E = 35;
	public static final int KEYCODE_F = 36;
	public static final int KEYCODE_G = 37;
	public static final int KEYCODE_H = 38;
	public static final int KEYCODE_I = 39;
	public static final int KEYCODE_J = 40;
	public static final int KEYCODE_K = 41;
	public static final int KEYCODE_L = 42;
	public static final int KEYCODE_M = 43;
	public static final int KEYCODE_N = 44;
	public static final int KEYCODE_O = 45;
	public static final int KEYCODE_P = 46;
	public static final int KEYCODE_Q = 47;
	public static final int KEYCODE_R = 48;
	public static final int KEYCODE_S = 49;
	public static final int KEYCODE_T = 50;
	public static final int KEYCODE_U = 51;
	public static final int KEYCODE_V = 52;
	public static final int KEYCODE_W = 53;
	public static final int KEYCODE_X = 54;
	public static final int KEYCODE_Y = 55;
	public static final int KEYCODE_Z = 56;
	public static final int KEYCODE_COMMA = 57;
	public static final int KEYCODE_PERIOD = 58;
	public static final int KEYCODE_ALT_LEFT = 59;
	public static final int KEYCODE_ALT_RIGHT = 60;
	public static final int KEYCODE_SHIFT_LEFT = 61;
	public static final int KEYCODE_SHIFT_RIGHT = 62;
	public static final int KEYCODE_TAB = 63;
	public static final int KEYCODE_SPACE = 64;
	public static final int KEYCODE_SYM = 65;
	public static final int KEYCODE_EXPLORER = 66;
	public static final int KEYCODE_ENVELOPE = 67;
	public static final int KEYCODE_ENTER = 68;
	public static final int KEYCODE_DEL = 69;
	public static final int KEYCODE_GRAVE = 70;
	public static final int KEYCODE_MINUS = 71;
	public static final int KEYCODE_EQUALS = 72;
	public static final int KEYCODE_LEFT_BRACKET = 73;
	public static final int KEYCODE_RIGHT_BRACKET = 74;
	public static final int KEYCODE_BACKSLASH = 75;
	public static final int KEYCODE_SEMICOLON = 76;
	public static final int KEYCODE_APOSTROPHE = 77;
	public static final int KEYCODE_SLASH = 78;
	public static final int KEYCODE_AT = 79;
	public static final int KEYCODE_NUM = 80;
	public static final int KEYCODE_HEADSETHOOK = 81;
	public static final int KEYCODE_FOCUS = 82;
	public static final int KEYCODE_PLUS = 83;
	public static final int KEYCODE_MENU = 82;
	public static final int KEYCODE_NOTIFICATION = 85;
	public static final int KEYCODE_SEARCH = 86;
	public static final int TAG_LAST_KEYCODE = 87;
	
	public static final int EV_SYN = 0x00;
	public static final int EV_ABS = 0x03;
	
	public static final int	ABS_MT_SLOT             = 0x2f;    /* MT slot being modified */
	public static final int	ABS_MT_TOUCH_MAJOR      = 0x30;    /* Major axis of touching ellipse */
	public static final int	ABS_MT_TOUCH_MINOR      = 0x31;    /* Minor axis (omit if circular) */
	public static final int	ABS_MT_WIDTH_MAJOR      = 0x32;    /* Major axis of approaching ellipse */
	public static final int	ABS_MT_WIDTH_MINOR      = 0x33;    /* Minor axis (omit if circular) */
	public static final int	ABS_MT_ORIENTATION      = 0x34;    /* Ellipse orientation */
	public static final int	ABS_MT_POSITION_X       = 0x35;    /* Center X touch position */
	public static final int	ABS_MT_POSITION_Y       = 0x36;    /* Center Y touch position */
	public static final int	ABS_MT_TOOL_TYPE        = 0x37;    /* Type of touching device */
	public static final int	ABS_MT_BLOB_ID          = 0x38;    /* Group a set of packets as a blob */
	public static final int	ABS_MT_TRACKING_ID      = 0x39;    /* Unique ID of initiated contact */
	public static final int	ABS_MT_PRESSURE         = 0x3a;    /* Pressure on contact area */
	public static final int	ABS_MT_DISTANCE         = 0x3b;    /* Contact hover distance */
	public static final int	ABS_MT_TOOL_X           = 0x3c;    /* Center X tool position */
	public static final int	ABS_MT_TOOL_Y           = 0x3d;    /* Center Y tool position */
}
